---
blank_issues_enabled: false
contact_links:
  - name: "ðŸ“• Documentation Issue"
    url: https://help.branch.io/developers-hub/docs/web-sdk-overview
    about: Report an issue in the Branch Web sdk Reference documentation by clicking "Suggest edits" button on the documenation page
  - name: "Branch Support"
    url: https://help.branch.io/using-branch/page/submit-a-ticket
    about: If you are having general trouble with Branch Web sdk or your Branch Web sdk integration, please reach out to Branch Support instead.
